### ISSUE TITLE
Add dark theme to favicon

### ISSUE THREAD

**Issue by lonely-lockley** [lonely-lockley/archinsight#51]
White favicon may be not visible for users using light color schemes. To make it visible in all conditions, several solutions may be considered:
- Try `@media (prefers-color-scheme: dark) {` style property for favicon in SVG format
- Place favicon logo into a dark (like github black #171515) circle

**Comment by Jaishree2310** [comment]
Can I take this issue? I am new to open source and would like to contribute to this.

**Comment by nexuspy** [comment]
can you, please assign it to me?

**Comment by lonely-lockley** [comment]
@Jaishree2310 you were first to respond. I can give you this issue. It may be challenging to setup and run the project, so feel free to make a working sample with a dummy html and I will explain how to prepare a PR. Ok?
You can find a favicon at the path: editor-ui/frontend/favicon.ico

**Comment by Jaishree2310** [comment]
@lonely-lockley thank you for assigning me. yes once dummy is ready you can help me with PR.

**Comment by lonely-lockley** [comment]
You will find an svg version of the logo here: editor-ui/frontend/static/archinsight-logo-no-background.svg
