### ISSUE TITLE
[Feature request] Store editor content on page refresh

### ISSUE THREAD

**Issue by lonely-lockley** [lonely-lockley/archinsight#7]
A very dangerous situation happens when a user unintentionally presses Ctrl+R: one can loose all editor content. Is there a way to keep it in case of unintentional page refresh?

**Comment by imn-d** [comment]
Need to choose a strategy:  saving on every change (harder) or saving when compile requested (easier and finished)

**Comment by lonely-lockley** [comment]
What do you mean under compiler request? Parsing source on client side or calling Compiler service?
I would save before parsing editor content, no matter what parse result will be. Content should be saved even if it's not correct.
Saving on Compiler service request will be a bad strategy cause it won't save on incorrect parse results

**Comment by imn-d** [comment]
@lonely-lockley Ok, code will be saved on every change. PR is ready for review
