### ISSUE TITLE
Fix an issue with import and declaration checks

### ISSUE THREAD

**Issue by lonely-lockley** [lonely-lockley/archinsight#79]
Fix an issue that imported element with the name A does not trigger "already declared" error while linking

**Comment by jwhitt3r** [comment]
Hay, would you be available to give some more detail on this issue, I would like to contribute if possible. What are the steps to reproduce, what is the location believed to have this issue so I can start looking.

**Comment by lonely-lockley** [comment]
Hi! Sure: the issue is in Translator service. To reproduce you can go to https://archinsight.org/playground and create two new files. This is the code for the first one:
```
context a
system a
    name = original A
```
This is for the second:
```
context b
import system a from context a
system b
    name = B
    links:
        -> a
system a
    name = duplicate A
```
You will see, that the diagram is rendered, but it should not, because `system a` declared in the second file duplicates imported `system a`. Translator should return error message about duplicated identifier `a`. 
The issue is somewhere around [this method](https://github.com/lonely-lockley/archinsight/blob/96cdefa0ab554f178437c4a91b4042b9e282c320/translator/src/main/java/com/github/lonelylockley/archinsight/link/Linker.java#L143)

**Comment by jwhitt3r** [comment]
Wicked, I shall have a look later today.

Thank you for the detailed response 👍

**Comment by lonely-lockley** [comment]
This fix is in production now. Congrats!

**Comment by jwhitt3r** [comment]
That's awesome thank you!
